### ISSUE TITLE
users_list API point changed

### ISSUE THREAD

**Issue by steffilazerte** [sckott/discgolf#12]
Looks like the API point for `users_list()` has changed, or at least this doesn't work for the ropensci forums:
```
library(disgolf)
user("steffilazerte") # No problem
users_list("active")  # Error: Not Found (HTTP 404)
```
Looking at the [Discourse API docs](https://docs.discourse.org/#tag/Users/paths/~1directory_items.json?period={period}&order={order}/get) it appears that it's a new url and format?

This gets the first 50 users with the option to paginate...

```
resp <- httr::GET(file.path(Sys.getenv("DISCOURSE_URL"), "directory_items.json"),
            query = list(period = "all", order = "days_visited"))
resp <- httr::content(resp, as = "parsed")
```

**Comment by sckott** [comment]
thanks!

`users_list` is for this route https://docs.discourse.org/#tag/Users/paths/~1admin~1users~1list~1{flag}.json/get - but correct that it's not working. not sure why. it seems to work in the browser

ahh, it seems they've changed auth key and username to be a request header instead of query param, which is a good change

**Comment by sckott** [comment]
should work now
